Add some verbosity

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -28,3 +28,10 @@ echo "-----> Building luvit"
 
 lit make lit://luvit/luvit
 chmod +x $BIN_DIR/luvit
+
+if [ ! -f $BIN_DIR/luvit ]; then
+	echo "Luvit binary not found after build step"
+	exit 1
+fi
+
+echo "Luvit built to $BIN_DIR/luvit" | indent
